#PARA UTILIZAR ESSES ENDPOINTS É NECESSÁRIO INSTALAR A EXTENSÃO DO VSCODE "REST CLIENT"
###

GET http://localhost:3333/clientes

###

POST http://localhost:3333/clientes
Content-Type: application/json

{
    "name": "ORELHA",
    "senha": "12345",
    "email": "COMUM",
    "telefone": "COMUM",
    "numero_quarto": "COMUM",
    "data_inicio": "COMUM",
    "data_saida": "COMUM"
}


  


###

PUT http://localhost:3333/clientes/id
Content-Type: application/json

{
    "name": "ORELHA",
    "password": "123",
    "profile": "ADM"
}

###

DELETE http://localhost:3333/clientes/id
